[package]
name = "di"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26", features = ["full"] }
reqwest = "0.11"
dotenv = "0.15"
dirs = "4"
